### ISSUE TITLE
Create google event from link

### ISSUE THREAD

**Issue by Safayy** [UoN-Computer-Science-Society/automatic-calendars#4]

**Comment by ecyht2** [comment]
I did research on this before. We can look into [ics/csv](https://support.google.com/calendar/answer/37118?hl=en&co=GENIE.Platform=Desktop) ics should also works for [outlook](https://support.microsoft.com/en-us/office/import-calendars-into-outlook-8e8364e1-400e-4c0f-a573-fe76b5a2d379) as well [(maybe even apple)](https://support.apple.com/en-my/guide/calendar/icl1023/mac) and vcard files which is the recommended file type when exporting and importing calendar events.

**Comment by ecyht2** [comment]
I also found a module in python called [icalendar](https://pypi.org/project/icalendar/) which follows the format proposed by [RFC5545](https://www.ietf.org/rfc/rfc5545.txt).

**Comment by Safayy** [comment]
That's a great project there. Would you be interested in this project forking from yours? To include additional functionality and a web fronted.

**Comment by ecyht2** [comment]
Yeah sure, and it is on pypi so we can use it by pip installing it. BTW for the virtual environment, I think it might be a better idea to provide a requirements.txt or using other packaging tool like [pipenv](https://pipenv.pypa.io/en/latest/) (Pipfile/Pipfile.lock). Some packages might be big and not ideal for git to manage.

Do keep in mind that I am working on v2.0.0 and it has some API changes.

**Comment by Safayy** [comment]
That sounds great, thanks. You're right there, I'll get on that. We'll keep that in mind.
